model: 'snake'
network: 'ro_34'
task: 'snake'
resume: False
gpus: (0, 1, 2, 3)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.5
    batch_size: 32
    dataset: 'MedicalTrain'
    scan_dir: '/media/cilab/DATA/Hila/Data/CT_hepatic_data_exp/CT_training/phases'
    init_mask_dir: '/media/cilab/DATA/Hila/Data/CT_hepatic_data_exp/CT_training/mask'
    gt_dir: '/media/cilab/DATA/Hila/Data/CT_hepatic_data_exp/CT_training/mask'
    num_workers: 32
    epoch: 140
test:
    dataset: 'MedicalVal'
    scan_dir: '/media/cilab/DATA/Hila/Data/CT_hepatic_data_exp/CT_training/phases'
    init_mask_dir: '/media/cilab/DATA/Hila/Data/CT_hepatic_data_exp/CT_training/mask'
    batch_size: 1

#heads: {'act_hm': 8, 'awh': 2}
heads: {'wh': 2}
segm_or_bbox: 'segm'

#segm_or_bbox: 'bbox'
#ct_score: 0.03
